branches:
  only:
    - master
language: cpp
dist: bionic
matrix:
  include:
    - name: "Linux / clang / x86_64"
      os: linux
      compiler: clang
    - name: "Linux / gcc / x86_64, i686"
      os: linux
      compiler: gcc
    - name: "Linux / gcc / aarch64"
      os: linux
      compiler: gcc
      arch: arm64
      # CMake picks up MSVC regardless of what compiler we specify here.
script:
  - ./ci/build
  - ./ci/test
deploy:
  provider: releases
  user: amarender-b
  password: MyGithub$2
  file_glob: true
  file: build-*/**/*
  skip_cleanup: true
  draft: true
